// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}

// app/page.tsx
"use client";

import { useApiClient } from "@/APIClient";
import { useState } from "react";

interface formData {
  email: string;
  password: string;
}

export default function Home() {
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const apiClient = useApiClient();

  const handleSubmit = async (e: React.SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();
    const data = { email, password };
    if (!email || !password) return window.alert("Please fill all the fields");
    const body = JSON.stringify(data);
    const method = "POST";
    const options = { method, body };
    await apiClient("/api/login", options);
  };

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Email"
          value={email}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setEmail(e.target.value)
          }
        />
        <input
          type="password"
          placeholder="Password"
          value={password}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setPassword(e.target.value)
          }
        />
        <button type="submit">Submit</button>
      </form>
    </div>
  );
}

// app/api/login/route.ts
import { NextRequest, NextResponse } from "next/server";
import { SignJWT } from "jose";
import { userCreds } from "@/userData";
import { cookies } from "next/headers";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const cookieStore = await cookies();
    const { email, password } = body;

    const user = userCreds.find((item) => item.email === email);
    if (!user) {
      return NextResponse.json({ error: "No User Found" }, { status: 404 });
    }

    if (user.password !== password) {
      return NextResponse.json({ error: "Invalid Password" }, { status: 401 });
    }

    const accessSecret = new TextEncoder().encode(
      process.env.NEXT_LOGIN_ACCESS_SECRET!,
    );
    const accessToken = await new SignJWT({ email })
      .setProtectedHeader({ alg: "HS256" })
      .setIssuedAt()
      .setExpirationTime("1h")
      .sign(accessSecret);

    const refreshSecret = new TextEncoder().encode(
      process.env.NEXT_LOGIN_REFRESH_SECRET!,
    );
    const refreshToken = await new SignJWT({ email })
      .setProtectedHeader({ alg: "HS256" })
      .setIssuedAt()
      .setExpirationTime("1h")
      .sign(refreshSecret);

    const isProd = process.env.NODE_ENV === "production";

    cookieStore.set({
      name: "token",
      value: refreshToken,
      httpOnly: true,
      path: "/",
      maxAge: 60 * 60 * 24 * 30,
      secure: isProd,
      sameSite: "lax",
    });

    return NextResponse.json(
      { message: "Login successful!", accessToken },
      { status: 200 },
    );
  } catch (err) {
    return NextResponse.json({ error: "Invalid Request" }, { status: 400 });
  }
}

// app/api/logout/route.ts
import { cookies } from "next/headers";
import { NextResponse } from "next/server";

export async function POST() {
  try {
    const cookieStore = await cookies();
    cookieStore.delete("token");
    return NextResponse.json({ message: "User logged out" }, { status: 200 });
  } catch (err) {
    return NextResponse.json({ error: "User logout failed" }, { status: 500 });
  }
}

// app/api/refresh/route.ts
import { userCreds } from "@/userData";
import { jwtVerify, SignJWT } from "jose";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";

export async function GET() {
  try {
    const cookieStore = await cookies();
    const cookieToken = cookieStore.has("token");

    if (!cookieToken) {
      return NextResponse.json(
        { error: "Refresh token not found" },
        { status: 401 },
      );
    }

    const token = cookieStore.get("token")?.value!;
    const refreshSecret = new TextEncoder().encode(
      process.env.NEXT_LOGIN_REFRESH_SECRET!,
    );
    const { payload } = await jwtVerify(token, refreshSecret);

    const user = userCreds.find((item) => item.email === payload.email);
    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const accessSecret = new TextEncoder().encode(
      process.env.NEXT_LOGIN_ACCESS_SECRET!,
    );
    const accessToken = await new SignJWT({ email: payload.email })
      .setProtectedHeader({ alg: "HS256" })
      .setIssuedAt()
      .setExpirationTime("1h")
      .sign(accessSecret);

    return NextResponse.json({
      accessToken,
      message: "Access token Refreshed",
    });
  } catch (err) {
    return NextResponse.json({ error: err }, { status: 500 });
  }
}

// context/auth.tsx
"use client";

import {
  createContext,
  Dispatch,
  ReactNode,
  SetStateAction,
  useContext,
  useRef,
  useState,
} from "react";

interface AuthContextType {
  token: string;
  setToken: Dispatch<SetStateAction<string>>;
  getAccessToken: () => Promise<string | null>;
  logout: () => Promise<void>;
  refresh: () => Promise<string | null>;
}
const AuthContext = createContext<AuthContextType | null>(null);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [token, setToken] = useState<string>("");

  const logout = async () => {
    await fetch("/api/logout", {
      method: "POST",
      credentials: "include",
      headers: { "Content-Type": "application/json" },
    });
    setToken("");
  };

  const refreshPromise = useRef<Promise<string | null> | null>(null);
  const refresh = async (): Promise<string | null> => {
    if (refreshPromise.current) return refreshPromise.current;

    refreshPromise.current = (async () => {
      try {
        const res = await fetch("/api/refresh", {
          method: "GET",
          credentials: "include",
          headers: { "Content-Type": "application/json" },
        });

        if (res.status == 500 || res.status == 404) {
          await logout();
          return null;
        }

        const authData = await res.json();
        const accessToken = authData.accessToken;
        setToken(accessToken);
        return accessToken;
      } catch (err) {
        await logout();
        throw new Error("Session Expired");
      } finally {
        refreshPromise.current = null;
      }
    })();
    return refreshPromise.current;
  };

  const getAccessToken = async (): Promise<string | null> => {
    if (token) {
      const data = JSON.parse(atob(token.split(".")[1]));
      const expiryTime = data.exp * 1000 - Date.now();
      if (expiryTime > 30_000) return token;
    }

    return refresh();
  };

  return (
    <AuthContext.Provider
      value={{ token, setToken, getAccessToken, logout, refresh }}
    >
      {children}
    </AuthContext.Provider>
  );
}

export const useAuth = () => {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error("useAuth must be used inside AuthProvider");
  return ctx;
};

// APIClient.tsx
import { useAuth } from "./context/auth";

export const useApiClient = () => {
  const { getAccessToken, logout } = useAuth();

  const client = async (url: string, options: RequestInit = {}) => {
    try {
      const accessToken = await getAccessToken();

      if (!accessToken) {
        await logout();
        return null;
      }

      const res = await fetch(url, {
        credentials: "include",
        ...options,
        headers: {
          ...options.headers,
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
      });

      const data = await res.json();
      if (!res.ok || data.status == 401) {
        throw new Error("Internal Server Error");
      }
      return data;
    } catch (err) {
      throw new Error(`Error: ${err}`);
    }
  };
  return client;
};
